### ISSUE TITLE
Sweep: Remove everything related to 'footnotes'

### ISSUE THREAD

**Issue by marioseixas** [marioseixas/marioseixas.github.io#21]
Remove everything related to 'footnotes' or 'footnote' because this github pages static site built with jekyll must show only its posts.

<details>
<summary>Checklist</summary>

- [ ] `_layouts/post.html`
> * Remove any HTML tags, CSS classes or ids related to 'footnotes'.

- [ ] `index.html`
> * Remove any HTML tags, CSS classes or ids related to 'footnotes'.

- [ ] `assets/js/search.js`
> * Remove any functions or variables related to 'footnotes'.
> • Remove any calls to these functions.

- [ ] `assets/js/tags.js`
> * Remove any functions or variables related to 'footnotes'.
> • Remove any calls to these functions.

- [ ] `_posts/2022-01-01-example-post.md`
> * Remove any markdown syntax related to 'footnotes'.

- [ ] `_posts/2023-08-14-hello-world.md`
> * Remove any markdown syntax related to 'footnotes'.

</details>

**Comment by kevinlu1248** [comment]
Hey I'm a developer at Sweep, we'll take a look at this.

**Comment by kevinlu1248** [comment]
Hey, @marioseixas can you list the files that should be modified? Not familiar with Jekyll but there should be one file that has all of this right?
